"""Export TensorFold's Metal source verbatim for the Zig/MLX-C host.

Development-only generator. The native executable embeds the generated sources;
it neither imports Python nor calls a Python subprocess. Run after kernel edits.
"""
import argparse
import ast
import json
from pathlib import Path

import mlx.core as mx
from tensorfold.kernels.qwen.dense.v1 import lane_qmm, lane_glue, lane_tree, lane_attention
from tensorfold.kernels.qwen.dense.v1 import row_attention, simd_qmm
from tensorfold.kernels.nemotron.lightning.v1 import kernels as nemotron, rows as nemotron_rows
from tensorfold.kernels.qwen.flash_next.v1 import kernels as flash

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "native" / "metal"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed sources differ from Python")
    args = parser.parse_args()
    if not args.check:
        OUT.mkdir(parents=True, exist_ok=True)

    def emit(path, content):
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale native kernel: {path}; rerun this tool without --check")
        else:
            path.write_text(content)

    original = mx.fast.metal_kernel
    mx.fast.metal_kernel = lambda **kwargs: kwargs
    definitions = []
    def export(key, spec):
        emit(OUT / f"{key}.metal", spec["source"])
        emit(OUT / f"{key}.h", spec.get("header", ""))
        ins = ", ".join(json.dumps(x) for x in spec["input_names"])
        outs = ", ".join(json.dumps(x) for x in spec["output_names"])
        contiguous = str(spec.get("ensure_row_contiguous", True)).lower()
        definitions.append(
            f'pub const {key} = Spec{{ .name = "{key}", '
            f'.inputs = &.{{{ins}}}, .outputs = &.{{{outs}}}, '
            f'.source = @embedFile("metal/{key}.metal"), '
            f'.header = @embedFile("metal/{key}.h"), .contiguous = {contiguous} }};'
        )
    try:
        for module, names in [
            (lane_qmm, ["xsum", "main", "main_tiled"]),
            (lane_glue, ["norm", "norm_nores", "gdn_pre", "gdn_post", "mlp_act"]),
            (lane_tree, ["tree", "replay"]),
            (lane_attention, ["tail", "tree_merge", "partial", "partial_direct"]),
            (row_attention, ["partial", "merge"]),
        ]:
            module._kernels.clear()
            for name in names:
                spec = module._kernel(name)
                key = module.__name__.rsplit(".", 1)[-1] + "_" + name
                export(key, spec)
        simd_qmm._kernels.clear()
        export("simd_qmm_mma", simd_qmm._compiled("mma", ()))
        # Extract static kernel declarations directly, preserving each module's header.
        # Dynamic source variants are enumerated below, so no model weights are needed.
        for module in (nemotron, nemotron_rows, flash):
            module._kernels.clear()
            tree = ast.parse(Path(module.__file__).read_text())
            for call in ast.walk(tree):
                if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Name)
                        and call.func.id == "_kernel" and call.args
                        and isinstance(call.args[0], ast.Constant)):
                    continue
                try:
                    spec = eval(compile(ast.Expression(call), module.__file__, "eval"), vars(module))
                except NameError:  # locally constructed add_norm variants below
                    continue
                export(call.args[0].value, spec)
        for kind, mix, inputs in [
            ("plain", nemotron._MIX_PLAIN, ["H", "X", "W", "eps"]),
            ("moe", nemotron._MIX_MOE, ["H", "Y", "WE", "SH", "W", "eps"]),
            ("experts", nemotron._MIX_EXPERTS, ["H", "Y", "WE", "W", "eps"]),
        ]:
            name = "nemotron_add_norm_" + kind
            export(name, nemotron._kernel(name, nemotron._ADD_NORM.replace("MIX", mix), inputs, ["HN", "OUT"]))
        for kind, branch, writeback, names in [
            ("none", "", "", ["H"]),
            ("plain", flash._BRANCH_PLAIN, flash._WRITEBACK, ["H", "INJ", "BR"]),
            ("grouped", flash._BRANCH_GROUPED, flash._WRITEBACK, ["H", "INJ", "Y", "WTS", "LG"]),
        ]:
            name = "q4_hc_norm_" + kind
            source = flash._HC_NORM.replace("BRANCH", branch).replace("WRITEBACK", writeback)
            export(name, flash._kernel(name, source, names, ["HN", "SSP"]))
        export("q4_router_float", flash._kernel("q4_router_float", flash._ROUTER.replace("OUT_T", "float"), ["X", "GW", "rows"], ["OUT"]))
    finally:
        mx.fast.metal_kernel = original
    emit(ROOT / "native" / "kernel_sources.zig",
        '// Generated by tools/export_native_kernels.py; do not edit.\n'
        'pub const Spec = struct { name: [:0]const u8, inputs: []const [:0]const u8, '
        'outputs: []const [:0]const u8, source: [:0]const u8, header: [:0]const u8, contiguous: bool };\n'
        + "\n".join(definitions) + "\n"
    )
    print(f"{'Checked' if args.check else 'Exported'} {len(definitions)} kernels in {OUT}")


if __name__ == "__main__":
    main()
