"""Inventory embedded kernels against native integration sites and replayed fixtures.

Run after test-variants passes. References establish integration, not execution;
numerical model integration evidence is recorded separately in native/COVERAGE.md.
"""
import argparse
import hashlib
import json
import re
from collections import Counter
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--fixtures", type=Path, default=Path("build/native-checks/variants/cases.json"))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    cases = json.loads(args.fixtures.read_text())
    counts = Counter(case["kernel"] for case in cases)
    catalog = re.findall(r"pub const (\w+) = Spec", (root / "native/kernel_sources.zig").read_text())
    references = {}
    for file in (root / "native").glob("*.zig"):
        if file.name in ("kernel_sources.zig", "variant_checks.zig", "failure_checks.zig"):
            continue
        for name in re.findall(r"src\.(\w+)", file.read_text()):
            references.setdefault(name, set()).add(file.name)
    rows = []
    for name in catalog:
        base = root / "native/metal" / name
        digest = hashlib.sha256((base.with_suffix(".h").read_text() + "\0" +
                                 base.with_suffix(".metal").read_text()).encode()).hexdigest()
        for case in cases:
            if case["kernel"] == name and case["source_sha256"] != digest:
                raise ValueError(f"Stale fixtures for {name}; rerun test-variants")
        sites = sorted(references.get(name, []))
        if not sites and not counts[name]:
            raise ValueError(f"No integration or native fixture coverage for {name}")
        rows.append(f"| `{name}` | {', '.join(f'`{site}`' for site in sites) or 'Diagnostic only'} | {counts[name]} |")
    content = "\n".join([
        "# Embedded Metal kernel inventory", "",
        f"{len(catalog)} embedded kernels; {sum(counts.values()):,} replayed launches across {len(counts)} variants.",
        "Generated by `tools/native_kernel_inventory.py` after `test-variants` passes.", "",
        "Integration columns are static call sites, not a claim that source references prove execution.",
        "The full-model, cache, draft and shared-utility execution evidence is in [COVERAGE.md](COVERAGE.md).",
        "A zero fixture count means that kernel is exercised by those integration/shared-utility suites",
        "rather than this optional-variant replay suite. Diagnostic entries are not production modes.", "",
        "| Embedded kernel | Native integration sites | Variant fixture launches |",
        "| --- | --- | ---: |", *rows, "",
    ])
    out = root / "native/KERNEL_INVENTORY.md"
    if args.check:
        if out.read_text() != content:
            raise SystemExit("Stale kernel inventory; regenerate after passing test-variants")
    else:
        out.write_text(content)
    print(f"{'Checked' if args.check else 'Wrote'} {len(catalog)} kernel entries")


if __name__ == "__main__":
    main()
