"""Inventory embedded kernels against native integration sites and replayed fixtures.

Run after the relevant Metal suites pass. References establish integration, not execution;
the current verification scope and executable checks are listed in native/README.md.
"""
import argparse
import hashlib
import json
import re
from collections import Counter
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--fixtures", type=Path, nargs="+")
    parser.add_argument("--output", type=Path, default=Path("build/native-checks/kernel-inventory.md"))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    fixtures = args.fixtures or [Path(f"build/native-checks/{name}/cases.json") for name in
                                 ("variants", "affine", "tensor-quantization", "bonsai", "gemma", "large-families", "row-attention")]
    cases = []
    for path in fixtures:
        if path.exists():
            cases.extend(json.loads(path.read_text()))
        elif args.fixtures:
            raise FileNotFoundError(path)
    if not cases:
        raise ValueError("No Metal fixtures; run the relevant build test targets first")
    counts = Counter(case["kernel"] for case in cases)
    catalog = re.findall(r"pub const (\w+) = Spec", (root / "native/kernel_sources.zig").read_text())
    references = {}
    for file in (root / "native").glob("*.zig"):
        if file.name in ("kernel_sources.zig", "variant_checks.zig", "failure_checks.zig"):
            continue
        code = file.read_text()
        names = re.findall(r"src\.(\w+)", code)
        names += re.findall(r'@import\("kernel_sources.zig"\)\.(\w+)', code)
        names += re.findall(r'@embedFile\("metal/(\w+)\.metal"\)', code)
        for name in names:
            references.setdefault(name, set()).add(file.name)
    rows = []
    for name in catalog:
        base = root / "native/metal" / name
        digest = hashlib.sha256((base.with_suffix(".h").read_text() + "\0" +
                                 base.with_suffix(".metal").read_text()).encode()).hexdigest()
        for case in cases:
            if case["kernel"] == name and case["source_sha256"] != digest:
                raise ValueError(f"Stale fixtures for {name}; rerun test-variants")
        sites = sorted(references.get(name, []))
        if not sites and not counts[name]:
            raise ValueError(f"No integration or native fixture coverage for {name}")
        rows.append(f"| `{name}` | {', '.join(f'`{site}`' for site in sites) or 'Diagnostic only'} | {counts[name]} |")
    content = "\n".join([
        "# Embedded Metal kernel inventory", "",
        f"{len(catalog)} embedded kernels; {sum(counts.values()):,} fixture launches across {len(counts)} variants.",
        "Generated by `tools/native_kernel_inventory.py`; fixture presence alone does not prove execution.", "",
        "Integration columns are static call sites, not a claim that source references prove execution.",
        "See native/README.md for executable parity checks and current verification limits.",
        "A zero count means this fixture set does not cover the kernel; other suites may cover it.",
        "Diagnostic entries are not production modes.", "",
        "| Embedded kernel | Native integration sites | Variant fixture launches |",
        "| --- | --- | ---: |", *rows, "",
    ])
    out = args.output
    if args.check:
        if out.read_text() != content:
            raise SystemExit("Stale kernel inventory; regenerate after passing test-variants")
    else:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content)
    print(f"{'Checked' if args.check else 'Wrote'} {len(catalog)} kernel entries")


if __name__ == "__main__":
    main()
